services:
  - type: web
    name: hinakira-accounting
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 180 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: DATABASE_URL
        fromDatabase:
          name: hinakira-db
          property: connectionString

databases:
  - name: hinakira-db
    plan: starter
